spring:
  mvc:
    cors:
      allowed-origins: "*"
  datasource:
    url: jdbc:postgresql://localhost:5433/ohwaiter
    username: ohwaiter
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true